// <auto-generated />
namespace GoodiesMarket.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Range_moved_to_seller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Range_moved_to_seller));
        
        string IMigrationMetadata.Id
        {
            get { return "201711082218592_Range_moved_to_seller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
