// <auto-generated />
namespace GoodiesMarket.Security.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initial_schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300228099_initial_schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
